name: Tests
on:
  pull_request:
    branches:
      - main
      - "release/**"
  push:
    branches:
      - main
      - "release/**"
  workflow_dispatch:
permissions:
  contents: read
jobs:
  macos:
    name: Xcode ${{ matrix.xcode-version }} / ${{ matrix.configuration }}
    runs-on: macos-15
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode-version }}.app
    steps:
      - name: Run checkout
        uses: actions/checkout@v4
      - name: Run tests
        run: |
          swift --version
          swift test --configuration ${{ matrix.configuration }}
    strategy:
      matrix:
        xcode-version:
          - "16.0"
          - "16.1"
          - "16.2"
          - "16.3"
          - "16.4"
        configuration:
          - debug
          - release
      fail-fast: false
